[package]
name = "esprit-demo"
version = "0.0.1"
authors = ["Dave Herman <dherman@mozilla.com>"]

[dependencies]
esprit = { version = "0.0.3", path = "../esprit" }
easter = { version = "0.0.3", path = "../esprit/crates/easter" }

